# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: Fenrier Lab
description: > #this means to ignore newlines until "nav_lists:"
  A Blog To Record And Share

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

# paths:
#   base: /
#   home: /
#   all:  /all.html
#   rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
# repository:  #e.g. someone/someone.github.io
# repository_tree:  #e.g. master

## Language & timezone ##
lang: zh #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
##timezone: Asia/Shanghai #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: seanwang
  email:  clouswang@gmail.com
  # facebook:  #your Facebook username
  # twitter:  #your Twitter username
  github:  SeanWangJS
  # googleplus:  #your Google+ username
  weibo:  Sudit
  # douban:  #your Douban username
  # linkedin:  #your Linkedin username

## Comment system (Disqus) ##
disqus:
  # shortname:  #the Disqus shortname for the site

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID:  'fab22ef3f9c9c7b0df5a'
  clientSecret:  'bd1913b44738e270a3af53e74d092cc1f8c98dd1'
  repository:  'SeanWangJS.github.io'
  owner:  'SeanWangJS'
  admin: ['SeanWangJS']
    # - owner

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site
google_analytics: UA-112476045-1

## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

# mathjax: true

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false